### PR TITLE
add get function name

### PR DESCRIPTION
**Pull request by mobailabs**
add get function name  
support

```
this.init = function()
```

```
this.init : function()
```

### CODE REVIEW

**Comment by SteveMcArthur** [comment]
I will look in to this. Hopefully tmo.

**Comment by SteveMcArthur** [comment]
@zhaopengme Thanks for the pull request. You are right that the extension is lacking the functionality to cope with the "this" function declaration. However, I am unable to merge your pull request. You need to submit pull requests on a separate branch from the master. I think there was also a more straight forward way to achieving what you are trying to do without a great deal of code changes. So what I've done is incorporated your idea into an update I have just pushed up myself. Will give you credit. Thanks :)

**Comment by SteveMcArthur** [comment]
@zhaopengme can you get back to me? I think we should consolidate our efforts and work together. You have created a duplicate copy of my brackets extension. My suggestion is that we cooperate to improve my existing extension.

**Comment by mobailabs** [comment]
Hi @SteveMcArthur . I have deleted my repositoriy.if you have some taks,can you tell me .or show task list.thanks.

**Comment by SteveMcArthur** [comment]
@zhaopengme The best thing you can do is give me feedback on whether the extension is working as expected. The extension was originally created to document a coffeescript project - so that is where it has been rigorously tested. JS is a different matter. I'm considering ideas used in the FuncDocr extension (https://github.com/wikunia/brackets-funcdocr).

**Comment by SteveMcArthur** [comment]
Can you delete your extension from the Brackets plugin registry? :)

**Pull request closed without merging**
